### ISSUE TITLE
First J4 Test

### ISSUE THREAD

**Issue by Heart1010** [Theophilix/EventTableEdit#1]
I did a first install of your j4 version - after that I exported your 'Normal table' from the demo site (as xml file). 
Then I imported the xml file on my site and added a new menu item for this normal table.

But by simply visiting this normal table site on the frontend I already get those two errors in the console. 

![image](https://user-images.githubusercontent.com/1481680/156257017-d506131a-cf43-4f40-8c0e-9cbb97aba4b2.png)

When I try to click in a cell to change something I get this
![image](https://user-images.githubusercontent.com/1481680/156257497-19827808-2a4e-4151-9f6f-e5564aaf6255.png)

**ok small update on that... the 404 error only appears when I have the eventtableedit menu item in a sub menu!** Do I change that menu item and place it with 'no parent item' (so directly in the root of the menu) **I can edit the cells!!!**

**Comment by Theophilix** [comment]
Hello,
this seems not to be a genuine ETE problem. I created a submenu in my demo and it works. Maybe a problem linked to an old template?

**Comment by Heart1010** [comment]
You're right - I disabled SEF in joomla config and then ETE is working on my J4 test site (with no parent and when ETE is in a submenu). As far as I enable SEF again it doesn't work in a submenu.

**Comment by Theophilix** [comment]
Fixed in 1.02 version.

**Comment by Heart1010** [comment]
Installed 1.02 - added a new 'Normal Table' and tested again.
Still getting the same error when the event table edit menu entry is under a parent item (sub menu) and SEF is enabled.

Here the error marked with the arrow is produced when I click in the marked cell.

![image](https://user-images.githubusercontent.com/1481680/204278820-404188d1-616f-4237-9e20-957605530697.png)

**Comment by Theophilix** [comment]
Thank you for the explanation. @vkrahu will work on it.

**Comment by vkrahu** [comment]
This issue is fixed. please download latest code.

**Comment by Heart1010** [comment]
> This issue is fixed. please download latest code.

Perfect - now it's working! Thanks @vkrahu 👍
